### ISSUE TITLE
tcl_climate not working anymore

### ISSUE THREAD

**Issue by ThorPrez** [lNikazzzl/tcl_ac_esphome#17]
[logs_esp-klima-kinderzimmer_run.txt](https://github.com/user-attachments/files/21583604/logs_esp-klima-kinderzimmer_run.txt)

Climate was working for a long time with HA core 2025.7.0.
Now after updating HA core and ESPHome to 2025.7.4 I got compile faults:

```
src/tcl_climate.h:593:98: error: invalid conversion from 'const char*' to 'long unsigned int' [-fpermissive]
src/tcl_climate.h:593:98: error: invalid conversion from 'const char*' to 'long long int' [-fpermissive]
src/tcl_climate.h:593:98: error: invalid conversion from 'const char*' to 'long long unsigned int' [-fpermissive]
```
and so on.
Any idea ?

**Comment by lucize** [comment]
please see #19
